version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
 build:
   executor:
     name: win/vs2019
     shell: powershell.exe
   steps:
     - checkout
     - run: docker run mcr.microsoft.com/windows/nanoserver:1809
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run App
         command:
           dotnet run
