version: 2.0
jobs:
 build:
   docker:
     - image: microsoft/servercore:10.0.14393.3686
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run App
         command:
           dotnet run
