version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
 build:
   executor:
     name: win/vs2019
     shell: powershell.exe
   steps:
     - checkout
#     - run: hostname
#     - run: |
#          [System.Environment]::OSVersion
#     - run: winver
     - run: docker run --name wincontainer mcr.microsoft.com/windows/nanoserver:1809
     - run: 
         name: Start Windows image container on top of OS
         command: docker start wincontainer
         background: true
     - run: docker ps -a
#     - run: docker start wincontainer
     - run: docker exec -i wincontainer hostname
#     - run: 
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run App
         command:
           dotnet run
