version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/framework/samples
   steps:
     - checkout
     - run: winver
 #    - run: |
 #         [System.Environment]::OSVersion
     - run: Install-WindowsFeature .NET-Framework-45-Features
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run App
         command:
           dotnet run
